/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chat.h"

bool_t
xdr_result_code (XDR *xdrs, result_code *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_result_code (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->descr, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_send_params (XDR *xdrs, send_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->to, 32))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cookie))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_login_params (XDR *xdrs, login_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->login, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->password, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_logout_params (XDR *xdrs, logout_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cookie))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_receive_params (XDR *xdrs, receive_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cookie))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_users_param (XDR *xdrs, users_param *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cookie))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_register_params (XDR *xdrs, register_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->login, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->password, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_login_result (XDR *xdrs, login_result *objp)
{
	register int32_t *buf;

	 if (!xdr_result (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cookie))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_receive_message (XDR *xdrs, receive_message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->from, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->message, 128))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_receive_result (XDR *xdrs, receive_result *objp)
{
	register int32_t *buf;

	 if (!xdr_result (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (receive_message), (xdrproc_t) xdr_receive_message))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_users_message (XDR *xdrs, users_message *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->login, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->online, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_users_result (XDR *xdrs, users_result *objp)
{
	register int32_t *buf;

	 if (!xdr_result (xdrs, &objp->res))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0,
		sizeof (users_message), (xdrproc_t) xdr_users_message))
		 return FALSE;
	return TRUE;
}
