/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chat.h"

using namespace std;
void user_menu(CLIENT *clnt, int id);
void menu(CLIENT *clnt);

void menu(CLIENT *clnt)
{
	register_params  register_arg;
	result  *result_register;
	login_result  *result_login;
	login_params  login_arg;
	int key;
	register_arg.login= new char[LOGIN_LEN];
	register_arg.password= new char[PASSWORD_LEN];
	login_arg.login= new char[LOGIN_LEN];
	login_arg.password= new char[PASSWORD_LEN];
	char login[LOGIN_LEN];
	char password[PASSWORD_LEN];
	cout<<"\n[1] Log in \n[2] Registration \n[3] Exit\n";
	cin>>key;
	if (cin.fail())
	{
		cout<<"Enter number 1,2 or 3\n";
		cin.clear();
		cin.ignore(256,'\n');
		menu(clnt);
	}
	switch (key)
	{
		case 1:
		{
			std::cout<<"Enter Login: ";
			cin>>login_arg.login;
			cout<<login_arg.login;
			cout<<"\nEnter Password: ";
			cin>>login_arg.password;
			result_login = login_2(&login_arg, clnt);
			if (result_login->res.code == OK)
			{
				cout<<"\n"<<result_login->res.descr<<endl;
				user_menu(clnt, result_login->cookie);
			} else {
				cout<<"\n"<<result_login->res.descr<<endl;
			}
			break;
		}
		case 2:
		{
			std::cout<<"Enter Login: ";
			cin>>register_arg.login;
			cout<<register_arg.login;
			cout<<"\nEnter Password: ";
			cin>>register_arg.password;
			result_register = register_2(&register_arg, clnt);
			if (result_register->code == OK)
			{
				cout<<"\nYou have successfully registered\n";	
			} else {
				cout<<"\nYou are not registered \n"<<result_register->descr<<endl;
			}
			break;
		}
		case 3:
		{
			exit(1);
		}
		default:
		cout<<"It is not a choise\n";
		break;
	}
	menu(clnt);
}

void user_menu(CLIENT *clnt, int id)
{
	int key;
	cout<<"\n[1]Show users\n[2]Receive massage \n[3]Send massage\n[4]Logout\n";
	cin>>key;
	if (cin.fail())
	{
		cout<<"Enter number 1, 2, 3 or 4\n";
		cin.clear();
		cin.ignore(256,'\n');
		user_menu(clnt, id);
	}
	switch (key)
	{
		case 1:
		{
			users_param  users_arg;
			users_result  *result_users;
			result_users = users_2(&users_arg, clnt);
			if (result_users->res.code == OK)
				{
					cout<<result_users->res.descr<<"\n\n";
					cout<<left<<setw(15)<<" User"<<"|  "<<setw(10)<<"Status"<<endl;
					for (int i=0; i< result_users->data.data_len; i++)
					{
						cout<<setw(15)<<result_users->data.data_val[i].login<<"|  "<<setw(10)<<result_users->data.data_val[i].online<<"\n";
					}
					cout<<"\nPress Enter to continue\n";
					cin.ignore();
					cin.ignore();
				} 
			else 
				{
					cout<<"\n Error: "<<result_users->res.descr<<"\n";
				}
			break;
		}
		case 2:
		{
			receive_params  receive_arg;
			receive_result  *result_receive;

			receive_arg.cookie = id;
			result_receive = receive_2(&receive_arg, clnt);

			if (result_receive->res.code == OK)
				{
					cout<<result_receive->res.descr<<"\n\n";
					cout<<left<<setw(15)<<" User"<<"|  "<<setw(40)<<"Message"<<endl;
					for (int i=0; i< result_receive->data.data_len; i++)
					{
						cout<<setw(15)<<result_receive->data.data_val[i].from<<"|  "<<setw(40)<<result_receive->data.data_val[i].message<<"\n";
					}
					cout<<"\nPress Enter to continue\n";
					cin.ignore();
					cin.ignore();
				} 
			else 
				{
					cout<<"\n Error: "<<result_receive->res.descr<<"\n";
				}
			break;
		}
		case 3:
		{
			result  *result_send;
			send_params  send_arg;
			string letter;
			send_arg.to = new char[LOGIN_LEN];
			cout<<"Enter username: ";
			cin>>send_arg.to;
			cout<<"\nEnter message: ";
			cin.ignore();
			getline(cin, letter);
			send_arg.message = new char[letter.length()+1];
			strcpy(send_arg.message, letter.c_str());
			send_arg.cookie = id;
			result_send = send_2(&send_arg, clnt);
			cout<<result_send->descr;
			break;
		}
		case 4:
		{
			logout_params  logout_arg;
			result  *result_logout;			
			logout_arg.cookie=id;
			result_logout = logout_2(&logout_arg, clnt);

			cout<<result_logout->descr<<"\n";
				
			menu(clnt);
			break;
		}
		default:
		break;
	}
	user_menu(clnt, id);
}

int
main (int argc, char *argv[])
{
	char *host;
	int id;
	CLIENT *clnt;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
		clnt = clnt_create (host, RPC_CHAT, RPC_CHAT_VERSION_2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	menu(clnt);
exit (0);
}
