/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chat.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpc_chat_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		send_params send_2_arg;
		login_params login_2_arg;
		logout_params logout_2_arg;
		receive_params receive_2_arg;
		users_param users_2_arg;
		register_params register_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SEND:
		_xdr_argument = (xdrproc_t) xdr_send_params;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (char *(*)(char *, struct svc_req *)) send_2_svc;
		break;

	case LOGIN:
		_xdr_argument = (xdrproc_t) xdr_login_params;
		_xdr_result = (xdrproc_t) xdr_login_result;
		local = (char *(*)(char *, struct svc_req *)) login_2_svc;
		break;

	case LOGOUT:
		_xdr_argument = (xdrproc_t) xdr_logout_params;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (char *(*)(char *, struct svc_req *)) logout_2_svc;
		break;

	case RECEIVE:
		_xdr_argument = (xdrproc_t) xdr_receive_params;
		_xdr_result = (xdrproc_t) xdr_receive_result;
		local = (char *(*)(char *, struct svc_req *)) receive_2_svc;
		break;

	case USERS:
		_xdr_argument = (xdrproc_t) xdr_users_param;
		_xdr_result = (xdrproc_t) xdr_users_result;
		local = (char *(*)(char *, struct svc_req *)) users_2_svc;
		break;

	case REGISTER:
		_xdr_argument = (xdrproc_t) xdr_register_params;
		_xdr_result = (xdrproc_t) xdr_result;
		local = (char *(*)(char *, struct svc_req *)) register_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPC_CHAT, RPC_CHAT_VERSION_2);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_CHAT, RPC_CHAT_VERSION_2, rpc_chat_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPC_CHAT, RPC_CHAT_VERSION_2, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPC_CHAT, RPC_CHAT_VERSION_2, rpc_chat_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPC_CHAT, RPC_CHAT_VERSION_2, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
