/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "chat.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

result *
send_2(send_params *argp, CLIENT *clnt)
{
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SEND,
		(xdrproc_t) xdr_send_params, (caddr_t) argp,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

login_result *
login_2(login_params *argp, CLIENT *clnt)
{
	static login_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOGIN,
		(xdrproc_t) xdr_login_params, (caddr_t) argp,
		(xdrproc_t) xdr_login_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

result *
logout_2(logout_params *argp, CLIENT *clnt)
{
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOGOUT,
		(xdrproc_t) xdr_logout_params, (caddr_t) argp,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

receive_result *
receive_2(receive_params *argp, CLIENT *clnt)
{
	static receive_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RECEIVE,
		(xdrproc_t) xdr_receive_params, (caddr_t) argp,
		(xdrproc_t) xdr_receive_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

users_result *
users_2(users_param *argp, CLIENT *clnt)
{
	static users_result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, USERS,
		(xdrproc_t) xdr_users_param, (caddr_t) argp,
		(xdrproc_t) xdr_users_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

result *
register_2(register_params *argp, CLIENT *clnt)
{
	static result clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTER,
		(xdrproc_t) xdr_register_params, (caddr_t) argp,
		(xdrproc_t) xdr_result, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
